import type { SkillProps } from "$lib/interfaces"

/** A list of my current skills */
export const skills: SkillProps[] = [
    {
        name: "React",
        abbreviation: "",
        description: "JavaScript library for building UIs",
        hasLogo: true,
        link: "reactjs.org",
    },
    {
        name: "Material UI",
        abbreviation: "MUI",
        description: "Component library for React",
        hasLogo: true,
        link: "mui.com",
    },
    {
        name: "Svelte",
        abbreviation: "",
        description: "Frontend compiler for building UIs",
        hasLogo: true,
        link: "svelte.dev",
    },
    {
        name: "Svelte Kit",
        abbreviation: "",
        description: "Frontend framework for Svelte",
        hasLogo: true,
        link: "kit.svelte.dev",
    },
    {
        name: "i18next",
        abbreviation: "",
        description: "Internationalization framework",
        hasLogo: true,
        link: "i18next.com",
    },
    {
        name: "Tailwind CSS",
        abbreviation: "",
        description: "Utility-first CSS framework",
        hasLogo: true,
        link: "tailwindcss.com",
    },
    {
        name: "daisyUI",
        abbreviation: "",
        description: "Component library for Tailwind",
        hasLogo: true,
        link: "daisyui.com",
    },
    {
        name: "Jest",
        abbreviation: "",
        description: "JavaScript testing framework",
        hasLogo: true,
        link: "jestjs.io",
    },
    {
        name: "Socket.IO",
        abbreviation: "",
        description: "Real-time JavaScript library",
        hasLogo: true,
        link: "socket.io",
    },
    {
        name: "p5.js",
        abbreviation: "",
        description: "JavaScript library for creativity",
        hasLogo: true,
        link: "p5js.org",
    },
    {
        name: "matter.js",
        abbreviation: "",
        description: "2D physics engine for the web",
        hasLogo: true,
        link: "brm.io/matter-js",
    },
    {
        name: "Node.js",
        abbreviation: "",
        description: "JavaScript run-time environment",
        hasLogo: true,
        link: "nodejs.dev",
    },
    {
        name: "Express",
        abbreviation: "ex",
        description: "Web framework for Node.js",
        hasLogo: false,
        link: "expressjs.com",
    },
    {
        name: "Spring Boot",
        abbreviation: "",
        description: "Extension for Java framework Spring",
        hasLogo: true,
        link: "spring.io",
    },
    {
        name: "OpenAPI",
        abbreviation: "",
        description: "Rest API specification standard",
        hasLogo: true,
        link: "openapis.org",
    },
    {
        name: "JavaScript",
        abbreviation: "JS",
        description: "Programming language of the web",
        hasLogo: true,
        link: "javascript.com",
    },
    {
        name: "TypeScript",
        abbreviation: "TS",
        description: "JavaScript with syntax for types",
        hasLogo: true,
        link: "typescriptlang.org",
    },
    {
        name: "Figma",
        abbreviation: "",
        description: "Tool for interface design",
        hasLogo: true,
        link: "figma.com",
    },
    {
        name: "Python",
        abbreviation: "",
        description: "High-level programming language",
        hasLogo: true,
        link: "python.org",
    },
    {
        name: "Arduino",
        abbreviation: "",
        description: "Microcontroller platform",
        hasLogo: true,
        link: "arduino.cc",
    },
    {
        name: "Onshape",
        abbreviation: "",
        description: "CAD software for 3D modeling",
        hasLogo: true,
        link: "onshape.com",
    },
    {
        name: "UltiMaker Cura",
        abbreviation: "",
        description: "Slicing software for 3D printing",
        hasLogo: true,
        link: "ultimaker.com",
    },
]
