import type { SkillProps } from "../../lib/interfaces";

export const skills: SkillProps[] = [
    {
        name: "React",
        abbreviation: "",
        description: "JavaScript library for building UIs",
        hasLogo: true,
        link: "reactjs.org",
    },
    {
        name: "Material UI",
        abbreviation: "MUI",
        description: "Component library for React",
        hasLogo: true,
        link: "mui.com",
    },
    {
        name: "Svelte",
        abbreviation: "",
        description: "Frontend compiler for building UIs",
        hasLogo: true,
        link: "svelte.dev",
    },
    {
        name: "Svelte Kit",
        abbreviation: "",
        description: "Frontend framework for svelte",
        hasLogo: true,
        link: "kit.svelte.dev",
    },
    {
        name: "Tailwind",
        abbreviation: "",
        description: "Utility-first CSS framework",
        hasLogo: true,
        link: "tailwindcss.com",
    },
    {
        name: "Jest",
        abbreviation: "",
        description: "JavaScript testing framework",
        hasLogo: true,
        link: "jestjs.io",
    },
    {
        name: "Socket.IO",
        abbreviation: "",
        description: "Real-time JavaScript library",
        hasLogo: true,
        link: "socket.io",
    },
    {
        name: "p5.js",
        abbreviation: "",
        description: "JavaScript library for creativity",
        hasLogo: true,
        link: "p5js.org",
    },
    {
        name: "matter.js",
        abbreviation: "",
        description: "2D physics engine for the web",
        hasLogo: true,
        link: "brm.io/matter-js",
    },
    {
        name: "Figma",
        abbreviation: "",
        description: "Tool for interface design",
        hasLogo: true,
        link: "figma.com",
    },
    {
        name: "Node.js",
        abbreviation: "",
        description: "JavaScript run-time environment",
        hasLogo: true,
        link: "nodejs.dev",
    },
    {
        name: "Express",
        abbreviation: "",
        description: "Web framework for Node.js",
        hasLogo: true,
        link: "expressjs.com",
    },
    {
        name: "OpenAPI",
        abbreviation: "",
        description: "Rest API specification standard",
        hasLogo: true,
        link: "openapis.org",
    },
    {
        name: "Git",
        abbreviation: "",
        description: "Version control system",
        hasLogo: true,
        link: "git-scm.com",
    },
    {
        name: "Structured Query Language",
        abbreviation: "SQL",
        description: "Database language",
        hasLogo: false,
        link: "wikipedia.org/wiki/SQL",
    },
    {
        name: "Representational State Transfer",
        abbreviation: "REST",
        description: "Software architectural style",
        hasLogo: false,
        link: "restfulapi.net",
    },
    {
        name: "Python",
        abbreviation: "",
        description: "High-level programming language",
        hasLogo: true,
        link: "python.org",
    },
    {
        name: "Arduino",
        abbreviation: "",
        description: "Microcontroller platform",
        hasLogo: true,
        link: "arduino.cc",
    },
    {
        name: "JavaScript",
        abbreviation: "JS",
        description: "Programming language of the web",
        hasLogo: true,
        link: "javascript.com",
    },
    {
        name: "TypeScript",
        abbreviation: "TS",
        description: "JavaScript with syntax for types",
        hasLogo: true,
        link: "typescriptlang.org",
    },
    {
        name: "Hypertext Markup Language",
        abbreviation: "HTML",
        description: "Markup language of the web",
        hasLogo: true,
        link: "w3.org/html",
    },
    {
        name: "Cascading Style Sheets",
        abbreviation: "CSS",
        description: "Style sheet language of the web",
        hasLogo: true,
        link: "w3.org/style/css",
    },
];
